theme: 
  - osuny-suggestions
  - osuny-campus-art-mediterrannee-footer
  - osuny
_merge: deep
params:
  debug:
    productionUrl: https://www.beauxartsdemarseille.fr
  logo:
    header: '/assets/images/logo.svg'
    footer: ''
  summary:
    position: hero
  search:
    active: true
    positions:
      - upper-menu
  home:
    head:
      title: site
  blocks:
    key_figures:
      animated: false
  events:
    index:
      sticky_dates: false
      highlight_exhibitions:
        future:
          options:
            image: true
            categories: false
      options:
        place: true
    list:
      with_more: true
    single:
      time_slots:
        date_format: "Monday 2 January 2006"
  posts:
    index:
      layout: grid
      taxonomies:
        display: true
        show_name: false
        layout: inline
    single:
      taxonomies:
        position: hero
  projects:
    index:
      layout: list
      options:
        categories: false
        image: false
        subtitle: false
        summary: false
        year: false
  programs:
    single:
      options:
        diploma_certification: true
  organizations:
    single:
      backlinks: true
  persons:
    single:
      backlinks: true
  image_sizes:
    sections:
      home:
        hero:
          tablet:   1200
          desktop:  1792
      events:
        layouts:
          agenda:
            tablet:   539
            desktop:  539
          parent:
            tablet:   539
            desktop:  539
          grid:
            desktop:  864
          list:
            desktop: 539